package dev.recica.drilon.tadoandroid.internal

internal object Constants {
    // <URLS
    private const val URL_TADO_BASE_URL = "https://my.tado.com/api/v2/"
    const val URL_TADO_CLIENT_SECRET_ENV = "https://my.tado.com/webapp/env.js"
    const val URL_TADO_TOKEN = "https://auth.tado.com/oauth/token"
    const val URL_TADO_HOME_INFO = "${URL_TADO_BASE_URL}me"
    const val URL_TADO_HOMES = "${URL_TADO_BASE_URL}homes/"
    // URLS>

    // <TOKENS
    const val FALLBACK_TADO_CLIENT_SECRET =
        "wZaRN7rpjn3FoNyF5IFuxg9uMzYJcvOoQ8QWiIqS3hfk6gLhVlG57j5YNoZL2Rtc"
    // TOKENS>

    // <JSON_KEYS
    const val JSON_KEY_CLIENT_SECRET_JAVASCRIPT_OBJECT = "clientSecret"
    const val JSON_KEY_CLIENT_SECRET = "client_secret"
    const val JSON_KEY_CONFIG = "config"
    const val JSON_KEY_OAUTH = "oauth"
    const val JSON_KEY_CLIENT_ID = "client_id"
    const val JSON_KEY_GRANT_TYPE = "grant_type"
    const val JSON_KEY_SCOPE = "scope"
    const val JSON_KEY_USERNAME = "username"
    const val JSON_KEY_PASSWORD = "password"
    const val JSON_KEY_ACCESS_TOKEN = "access_token"
    const val JSON_KEY_REFRESH_TOKEN = "refresh_token"
    const val JSON_KEY_AUTHORIZATION = "Authorization"
    const val JSON_KEY_BEARER = "Bearer"
    const val JSON_KEY_HOMES = "homes"
    const val JSON_KEY_ID = "id"
    const val JSON_KEY_CONTENT_TYPE = "Content-type"
    const val JSON_KEY_CONTENT_TYPE_VALUE = "application/json;charset=UTF-8"
    const val JSON_KEY_CLIENT_ID_VALUE = "tado-web-app"
    const val JSON_KEY_SCOPE_VALUE = "home.user"
    const val JSON_KEY_ERRORS = "errors"
    const val JSON_KEY_CODE = "code"
    const val JSON_KEY_TITLE = "title"
    const val JSON_KEY_NAME = "name"
    const val JSON_KEY_EMAIL = "email"
    const val JSON_KEY_PHONE = "phone"
    const val JSON_KEY_DATE_CREATED = "dateCreated"
    const val JSON_KEY_CONTACT_DETAILS = "contactDetails"
    const val JSON_KEY_ADDRESS = "address"
    const val JSON_KEY_ADDRESS_LINE_1 = "addressLine1"
    const val JSON_KEY_ADDRESS_LINE_2 = "addressLine2"
    const val JSON_KEY_ZIP_CODE = "zipCode"
    const val JSON_KEY_CITY = "city"
    const val JSON_KEY_STATE = "state"
    const val JSON_KEY_COUNTRY = "country"
    const val JSON_KEY_GEOLOCATION = "geolocation"
    const val JSON_KEY_LATITUDE = "latitude"
    const val JSON_KEY_LONGITUDE = "longitude"
    const val JSON_KEY_DATE_TIME_ZONE = "dateTimeZone"
    const val JSON_KEY_TEMPERATURE_UNIT = "temperatureUnit"
    const val JSON_KEY_INSTALLATION_COMPLETED = "installationCompleted"
    const val JSON_KEY_SIMPLE_SMART_SCHEDULE_ENABLED = "simpleSmartScheduleEnabled"
    const val JSON_KEY_AWAY_RADIUS_IN_METERS = "awayRadiusInMeters"
    const val JSON_KEY_USE_PRE_SKILL_APPS = "usePreSkillsApps"
    const val JSON_KEY_CHRISTMAS_MODE_ENABLED = "christmasModeEnabled"
    const val JSON_KEY_CONSENT_GRANT_SKIPPABLE = "consentGrantSkippable"
    const val JSON_KEY_DEVICE_TYPES = "deviceTypes"
    const val JSON_KEY_DEVICES = "devices"
    const val JSON_KEY_CONNECTION_STATE = "connectionState"
    const val JSON_KEY_TIMESTAMP = "timestamp"
    const val JSON_KEY_VALUE = "value"
    const val JSON_KEY_CHARACTERISTICS = "characteristics"
    const val JSON_KEY_CAPABILITIES = "capabilities"
    const val JSON_KEY_DUTIES = "duties"
    const val JSON_KEY_DEVICE_TYPE = "deviceType"
    const val JSON_KEY_SERIAL_NO = "serialNo"
    const val JSON_KEY_SHORT_SERIAL_NO = "shortSerialNo"
    const val JSON_KEY_CURRENT_FW_VERSION = "currentFwVersion"
    const val JSON_KEY_IN_PAIRING_MODE = "inPairingMode"
    const val JSON_KEY_BATTERY_STATE = "batteryState"
    const val JSON_KEY_DAZZLE_MODE = "dazzleMode"
    const val JSON_KEY_SUPPORTED = "supported"
    const val JSON_KEY_ENABLED = "enabled"
    const val JSON_KEY_OPEN_WINDOW_DETECTION = "openWindowDetection"
    const val JSON_KEY_TIME_OUT_IN_SECONDS = "timeoutInSeconds"
    const val JSON_KEY_TYPE = "type"
    const val JSON_KEY_REPORT_AVAILABLE = "reportAvailable"
    const val JSON_KEY_SUPPORTS_DAZZLE = "supportsDazzle"
    const val JSON_KEY_DAZZLE_ENABLED = "dazzleEnabled"
    const val JSON_KEY_PRESENCE = "presence"
    const val JSON_KEY_TEMPERATURE = "temperature"
    const val JSON_KEY_CELSIUS = "celsius"
    const val JSON_KEY_FAHRENHEIT = "fahrenheit"
    const val JSON_KEY_PRECISION = "precision"
    const val JSON_KEY_PERCENTAGE = "percentage"
    const val JSON_KEY_SOLAR_INTENSITY = "solarIntensity"
    const val JSON_KEY_OUTSIDE_TEMPERATURE = "outsideTemperature"
    const val JSON_KEY_WEATHER_STATE = "weatherState"
    const val JSON_KEY_GEOLOCATION_OVERRIDE_DISABLE_TIME = "geolocationOverrideDisableTime"
    const val JSON_KEY_SETTING = "setting"
    const val JSON_KEY_POWER = "power"
    const val JSON_KEY_ON = "ON"
    const val JSON_KEY_OFF = "OFF"
    const val JSON_KEY_TERMINATION = "termination"
    const val JSON_KEY_NEXT_SCHEDULE_CHANGE = "nextScheduleChange"
    const val JSON_KEY_START = "start"
    const val JSON_KEY_ACTIVITY_DATA_POINTS = "activityDataPoints"
    const val JSON_KEY_SENSOR_DATA_POINTS = "sensorDataPoints"
    const val JSON_KEY_TADO_MODE_FOR_ZONE = "tadoMode"
    const val JSON_KEY_GEOLOCATION_OVERRIDE = "geolocationOverride"
    const val JSON_KEY_LINK = "link"
    const val JSON_KEY_REVISION = "revision"
    const val JSON_KEY_MOBILE_DEVICES = "mobileDevices"
    const val JSON_KEY_LOCALE = "locale"
    const val JSON_KEY_GEP_TRACKING_ENABLED = "geoTrackingEnabled"
    const val JSON_KEY_HOME_PRESENCE = "homePresence"
    const val JSON_KEY_SETTINGS = "settings"
    const val JSON_KEY_LOCATION = "location"
    const val JSON_KEY_STALE = "stale"
    const val JSON_KEY_AT_HOME = "atHome"
    const val JSON_KEY_BEARING_FROM_HOME = "bearingFromHome"
    const val JSON_KEY_DEGREES = "degrees"
    const val JSON_KEY_RADIANS = "radians"
    const val JSON_KEY_RELATIVE_DISTANCE_FROM_HOME_FENCE = "relativeDistanceFromHomeFence"
    const val JSON_KEY_DEVICE_METADATA = "deviceMetadata"
    const val JSON_KEY_PLATFORM = "platform"
    const val JSON_KEY_OS_VERSION = "osVersion"
    const val JSON_KEY_MODEL = "model"
    const val JSON_KEY_EXPIRY = "expiry"
    const val JSON_KEY_PROJECTED_EXPIRY = "projectedExpiry"
    const val JSON_KEY_TYPE_SKILL_BASED_APP = "typeSkillBasedApp"
    const val JSON_KEY_DURATION_IN_SECONDS = "durationInSeconds"
    const val JSON_KEY_REMAINING_TIME_IN_SECONDS = "remainingTimeInSeconds"
    const val JSON_KEY_TIMER = "TIMER"
    const val JSON_KEY_MANUAL = "MANUAL"
    const val JSON_KEY_TADO_MODE_FOR_OVERLAY = "TADO_MODE"
    const val JSON_KEY_HEATING = "HEATING"
    // JSON_KEYS>
}